"""create evaluations table

Revision ID: bb7c5507c50a
Revises: 9fa5b51c93fa
Create Date: 2026-09-07 23:25:45.917729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb7c5507c50a'
down_revision: Union[str, Sequence[str], None] = '9fa5b51c93fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_submission_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('kpi_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('innovation_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('feasibility_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('impact_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Enum('RECOMMEND', 'DO_NOT_RECOMMEND', name='evaluationrecommendation'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', name='evaluationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_submission_id'], ['pilot_submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluations')
    # ### end Alembic commands ###
