"""create contracts table

Revision ID: e9781a64470a
Revises: bb7c5507c50a
Create Date: 2026-09-07 23:28:43.603706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9781a64470a'
down_revision: Union[str, Sequence[str], None] = 'bb7c5507c50a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('startup_id', sa.Integer(), nullable=False),
    sa.Column('pilot_id', sa.Integer(), nullable=False),
    sa.Column('government_user_id', sa.Integer(), nullable=False),
    sa.Column('contract_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'AWARDED', 'ACTIVE', 'COMPLETED', 'TERMINATED', name='contractstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['government_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_id'], ['pilots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['startup_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    # ### end Alembic commands ###
